In [2]:
# In kaggle v33026.ipynb, I only included the audio files from train_soundscapes.
# In this file, I also include the audio files from train_audio.

import librosa
import numpy as np
import pandas as pd
import os
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

In [26]:
train_soundscapes_labels_df = pd.read_csv("train_soundscapes_labels.csv")

train_soundscapes_reduced_df = pd.DataFrame({
    "filename": train_soundscapes_labels_df.iloc[:, :2].astype(str).agg(''.join, axis=1),
    "primary_label": train_soundscapes_labels_df.iloc[:, 3]
})

In [9]:
train_soundscapes_labels_df.head(5)

,filename,start,end,primary_label
0,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:00,00:00:05,22961;23158;24321;517063;65380
1,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:05,00:00:10,22961;23158;24321;517063;65380
2,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:10,00:00:15,22961;23158;24321;517063;65380
3,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:15,00:00:20,22961;23158;24321;517063;65380
4,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:20,00:00:25,22961;23158;24321;517063;65380

In [10]:
train_soundscapes_reduced_df.head(5)

,filename,primary_label
0,BC2026_Train_0039_S22_20211231_201500.ogg00:00:00,22961;23158;24321;517063;65380
1,BC2026_Train_0039_S22_20211231_201500.ogg00:00:05,22961;23158;24321;517063;65380
2,BC2026_Train_0039_S22_20211231_201500.ogg00:00:10,22961;23158;24321;517063;65380
3,BC2026_Train_0039_S22_20211231_201500.ogg00:00:15,22961;23158;24321;517063;65380
4,BC2026_Train_0039_S22_20211231_201500.ogg00:00:20,22961;23158;24321;517063;65380

In [11]:
len(train_soundscapes_reduced_df)

1478

In [27]:
taxonomy_df = pd.read_csv("taxonomy.csv")
classes = ['Insecta', 'Reptilia', 'Amphibia', 'Mammalia', 'Aves']
filenames = {value: [] for value in classes}

for entry in train_soundscapes_reduced_df.itertuples():
    filename = entry.filename
    primary_label = entry.primary_label.split(';')

    found = {value: False for value in classes}
    
    for label in primary_label:
        for value in classes:
            if taxonomy_df[taxonomy_df['primary_label'] == label]['class_name'].values[0] == value:
                found[value] = True
    
    for value in classes:
         if found[value]:
            filenames[value].append(filename)

In [28]:
# train_audio has 206 folders, each folder corresponds to a primary label.

folder_path = "train_audio"

num_folders = sum(
    os.path.isdir(os.path.join(folder_path, item))
    for item in os.listdir(folder_path)
)

print(num_folders)

206

In [29]:
# train_audio has 206 folders, each folder corresponds to a primary label.
# The files in train_soundscapes_reduced_df are all 5 seconds, but the ones in train_audio vary in length.
# This block classifies all of the sound files in train_audio_df.csv
# When we make a model, we will split these files into 5 second intervals.

# One issue is that there are 235 species.

# This code takes 10 minutes to run.

from time import time

start_time = time()

train_audio_df = pd.DataFrame(columns=['filename', 'primary_label'])

item_count = 0

for item in os.listdir(folder_path):
    item_count += 1
    if os.path.isdir(os.path.join(folder_path, item)):
        primary_label = taxonomy_df[taxonomy_df['primary_label'] == item]['class_name'].values[0]
        for file in os.listdir(os.path.join(folder_path, item)):
            if file.endswith('.ogg'):
                
                filename = os.path.join(item, file)

                audio, sr = librosa.load(os.path.join(folder_path, item, file), sr=None)
                duration = librosa.get_duration(y=audio, sr=sr)
                
                if duration >= 5:
                    # Add filename and class to file.
                    train_audio_df.loc[len(train_audio_df)] = [filename, primary_label]

    print(f"Time taken: {time() - start_time} seconds")
    print(f"Items processed: {item_count}")

Time taken: 2.260925054550171 seconds
Items processed: 1
Time taken: 8.082215070724487 seconds
Items processed: 2
Time taken: 15.178282022476196 seconds
Items processed: 3
Time taken: 15.702569007873535 seconds
Items processed: 4
Time taken: 18.61775302886963 seconds
Items processed: 5
Time taken: 18.69682288169861 seconds
Items processed: 6
Time taken: 19.70902991294861 seconds
Items processed: 7
Time taken: 19.73676300048828 seconds
Items processed: 8
Time taken: 29.770681858062744 seconds
Items processed: 9
Time taken: 36.55143213272095 seconds
Items processed: 10
Time taken: 39.93571209907532 seconds
Items processed: 11
Time taken: 39.967047929763794 seconds
Items processed: 12
Time taken: 43.087323904037476 seconds
Items processed: 13
Time taken: 43.1636381149292 seconds
Items processed: 14
Time taken: 43.39476799964905 seconds
Items processed: 15
Time taken: 43.97493600845337 seconds
Items processed: 16
Time taken: 44.38703489303589 seconds
Items processed: 17
Time taken: 46.296411991119385 seconds
Items processed: 18
Time taken: 63.02049803733826 seconds
Items processed: 19
Time taken: 65.96262192726135 seconds
Items processed: 20
Time taken: 68.97612714767456 seconds
Items processed: 21
Time taken: 70.52693510055542 seconds
Items processed: 22
Time taken: 77.84104990959167 seconds
Items processed: 23
Time taken: 81.5466251373291 seconds
Items processed: 24
Time taken: 85.75537395477295 seconds
Items processed: 25
Time taken: 88.09110903739929 seconds
Items processed: 26
Time taken: 93.18071508407593 seconds
Items processed: 27
Time taken: 93.42716717720032 seconds
Items processed: 28
Time taken: 95.2982668876648 seconds
Items processed: 29
Time taken: 98.34676480293274 seconds
Items processed: 30
Time taken: 101.52304601669312 seconds
Items processed: 31
Time taken: 103.82623505592346 seconds
Items processed: 32
Time taken: 105.84365797042847 seconds
Items processed: 33
Time taken: 107.62445592880249 seconds
Items processed: 34
Time taken: 109.83013486862183 seconds
Items processed: 35
Time taken: 110.95417618751526 seconds
Items processed: 36
Time taken: 111.05721187591553 seconds
Items processed: 37
Time taken: 111.73324704170227 seconds
Items processed: 38
Time taken: 112.76575088500977 seconds
Items processed: 39
Time taken: 113.40133094787598 seconds
Items processed: 40
Time taken: 114.95466899871826 seconds
Items processed: 41
Time taken: 115.06585788726807 seconds
Items processed: 42
Time taken: 117.6792459487915 seconds
Items processed: 43
Time taken: 118.98975801467896 seconds
Items processed: 44
Time taken: 123.10823106765747 seconds
Items processed: 45
Time taken: 124.37205410003662 seconds
Items processed: 46
Time taken: 126.90845704078674 seconds
Items processed: 47
Time taken: 128.22380089759827 seconds
Items processed: 48
Time taken: 130.53745484352112 seconds
Items processed: 49
Time taken: 134.587975025177 seconds
Items processed: 50
Time taken: 136.12505984306335 seconds
Items processed: 51
Time taken: 136.18988490104675 seconds
Items processed: 52
Time taken: 137.6684229373932 seconds
Items processed: 53
Time taken: 140.4644660949707 seconds
Items processed: 54
Time taken: 144.27139687538147 seconds
Items processed: 55
Time taken: 152.07657194137573 seconds
Items processed: 56
Time taken: 152.37714290618896 seconds
Items processed: 57
Time taken: 152.67818999290466 seconds
Items processed: 58
Time taken: 159.8247230052948 seconds
Items processed: 59
Time taken: 161.02902102470398 seconds
Items processed: 60
Time taken: 161.08891820907593 seconds
Items processed: 61
Time taken: 163.9203019142151 seconds
Items processed: 62
Time taken: 164.11004996299744 seconds
Items processed: 63
Time taken: 171.10647988319397 seconds
Items processed: 64
Time taken: 173.2795910835266 seconds
Items processed: 65
Time taken: 175.06198692321777 seconds
Items processed: 66
Time taken: 177.09930515289307 seconds
Items processed: 67
Time taken: 178.60540199279785 seconds
Items processed: 68
Time taken: 180.17542004585266 seconds
Items processed: 69
Time taken: 182.97238683700562 seconds
Items processed: 70
Time taken: 188.46016597747803 seconds
Items processed: 71
Time taken: 190.9576861858368 seconds
Items processed: 72
Time taken: 192.0121030807495 seconds
Items processed: 73
Time taken: 192.0757839679718 seconds
Items processed: 74
Time taken: 195.97437286376953 seconds
Items processed: 75
Time taken: 205.8631329536438 seconds
Items processed: 76
Time taken: 205.8822419643402 seconds
Items processed: 77
Time taken: 213.00601410865784 seconds
Items processed: 78
Time taken: 216.24237704277039 seconds
Items processed: 79
Time taken: 217.8608889579773 seconds
Items processed: 80
Time taken: 217.98440718650818 seconds
Items processed: 81
Time taken: 221.53332114219666 seconds
Items processed: 82
Time taken: 222.3124840259552 seconds
Items processed: 83
Time taken: 225.358500957489 seconds
Items processed: 84
Time taken: 228.97394704818726 seconds
Items processed: 85
Time taken: 229.71020102500916 seconds
Items processed: 86
Time taken: 234.5880789756775 seconds
Items processed: 87
Time taken: 238.01839900016785 seconds
Items processed: 88
Time taken: 245.4945821762085 seconds
Items processed: 89
Time taken: 255.57514095306396 seconds
Items processed: 90
Time taken: 259.9214539527893 seconds
Items processed: 91
Time taken: 260.8557479381561 seconds
Items processed: 92
Time taken: 262.26089787483215 seconds
Items processed: 93
Time taken: 267.18440413475037 seconds
Items processed: 94
Time taken: 268.83013796806335 seconds
Items processed: 95
Time taken: 269.56419587135315 seconds
Items processed: 96
Time taken: 273.5090289115906 seconds
Items processed: 97
Time taken: 275.2505340576172 seconds
Items processed: 98
Time taken: 275.3598120212555 seconds
Items processed: 99
Time taken: 280.58555912971497 seconds
Items processed: 100
Time taken: 286.6276240348816 seconds
Items processed: 101
Time taken: 288.829283952713 seconds
Items processed: 102
Time taken: 290.89998507499695 seconds
Items processed: 103
Time taken: 293.8272569179535 seconds
Items processed: 104
Time taken: 296.05177998542786 seconds
Items processed: 105
Time taken: 297.0508050918579 seconds
Items processed: 106
Time taken: 298.06128191947937 seconds
Items processed: 107
Time taken: 302.5804560184479 seconds
Items processed: 108
Time taken: 306.4104299545288 seconds
Items processed: 109
Time taken: 307.5769820213318 seconds
Items processed: 110
Time taken: 307.6531631946564 seconds
Items processed: 111
Time taken: 315.2006208896637 seconds
Items processed: 112
Time taken: 318.5097758769989 seconds
Items processed: 113
Time taken: 319.96199202537537 seconds
Items processed: 114
Time taken: 319.98421001434326 seconds
Items processed: 115
Time taken: 321.90466594696045 seconds
Items processed: 116
Time taken: 330.1135518550873 seconds
Items processed: 117
Time taken: 331.87852597236633 seconds
Items processed: 118
Time taken: 337.0368800163269 seconds
Items processed: 119
Time taken: 343.9426898956299 seconds
Items processed: 120
Time taken: 349.06489300727844 seconds
Items processed: 121
Time taken: 354.9900200366974 seconds
Items processed: 122
Time taken: 361.2786729335785 seconds
Items processed: 123
Time taken: 361.5259759426117 seconds
Items processed: 124
Time taken: 362.5371301174164 seconds
Items processed: 125
Time taken: 371.4643201828003 seconds
Items processed: 126
Time taken: 379.6788911819458 seconds
Items processed: 127
Time taken: 386.6574459075928 seconds
Items processed: 128
Time taken: 386.71177196502686 seconds
Items processed: 129
Time taken: 393.11492586135864 seconds
Items processed: 130
Time taken: 404.4846999645233 seconds
Items processed: 131
Time taken: 404.91855120658875 seconds
Items processed: 132
Time taken: 413.85190892219543 seconds
Items processed: 133
Time taken: 414.78241205215454 seconds
Items processed: 134
Time taken: 415.0211730003357 seconds
Items processed: 135
Time taken: 419.0155599117279 seconds
Items processed: 136
Time taken: 419.0644619464874 seconds
Items processed: 137
Time taken: 419.3015880584717 seconds
Items processed: 138
Time taken: 423.4001500606537 seconds
Items processed: 139
Time taken: 427.54275393486023 seconds
Items processed: 140
Time taken: 429.1209008693695 seconds
Items processed: 141
Time taken: 429.13449788093567 seconds
Items processed: 142
Time taken: 430.0443642139435 seconds
Items processed: 143
Time taken: 432.3981809616089 seconds
Items processed: 144
Time taken: 433.67069387435913 seconds
Items processed: 145
Time taken: 435.5815498828888 seconds
Items processed: 146
Time taken: 435.91726183891296 seconds
Items processed: 147
Time taken: 437.92219614982605 seconds
Items processed: 148
Time taken: 439.719055891037 seconds
Items processed: 149
Time taken: 449.3331570625305 seconds
Items processed: 150
Time taken: 449.3450450897217 seconds
Items processed: 151
Time taken: 455.9363160133362 seconds
Items processed: 152
Time taken: 465.0565688610077 seconds
Items processed: 153
Time taken: 468.1335549354553 seconds
Items processed: 154
Time taken: 470.9735760688782 seconds
Items processed: 155
Time taken: 473.73781991004944 seconds
Items processed: 156
Time taken: 474.03587102890015 seconds
Items processed: 157
Time taken: 485.85925483703613 seconds
Items processed: 158
Time taken: 487.32056403160095 seconds
Items processed: 159
Time taken: 488.99196910858154 seconds
Items processed: 160
Time taken: 488.99780011177063 seconds
Items processed: 161
Time taken: 494.8864200115204 seconds
Items processed: 162
Time taken: 501.3337800502777 seconds
Items processed: 163
Time taken: 501.34911704063416 seconds
Items processed: 164
Time taken: 505.0815010070801 seconds
Items processed: 165
Time taken: 507.2875521183014 seconds
Items processed: 166
Time taken: 510.272677898407 seconds
Items processed: 167
Time taken: 518.2661819458008 seconds
Items processed: 168
Time taken: 518.9655981063843 seconds
Items processed: 169
Time taken: 520.2446370124817 seconds
Items processed: 170
Time taken: 521.4701929092407 seconds
Items processed: 171
Time taken: 524.5103378295898 seconds
Items processed: 172
Time taken: 530.0536878108978 seconds
Items processed: 173
Time taken: 530.2254438400269 seconds
Items processed: 174
Time taken: 538.5188670158386 seconds
Items processed: 175
Time taken: 538.5428781509399 seconds
Items processed: 176
Time taken: 539.9742429256439 seconds
Items processed: 177
Time taken: 543.8240721225739 seconds
Items processed: 178
Time taken: 546.5373132228851 seconds
Items processed: 179
Time taken: 546.5936160087585 seconds
Items processed: 180
Time taken: 548.3430738449097 seconds
Items processed: 181
Time taken: 549.0177710056305 seconds
Items processed: 182
Time taken: 551.8507740497589 seconds
Items processed: 183
Time taken: 555.8515841960907 seconds
Items processed: 184
Time taken: 556.2922599315643 seconds
Items processed: 185
Time taken: 557.9599370956421 seconds
Items processed: 186
Time taken: 558.050961971283 seconds
Items processed: 187
Time taken: 558.7089900970459 seconds
Items processed: 188
Time taken: 562.7613310813904 seconds
Items processed: 189
Time taken: 562.7867751121521 seconds
Items processed: 190
Time taken: 564.2111899852753 seconds
Items processed: 191
Time taken: 567.5014591217041 seconds
Items processed: 192
Time taken: 575.9128000736237 seconds
Items processed: 193
Time taken: 579.640823841095 seconds
Items processed: 194
Time taken: 579.9005560874939 seconds
Items processed: 195
Time taken: 580.0824630260468 seconds
Items processed: 196
Time taken: 580.9178240299225 seconds
Items processed: 197
Time taken: 590.746463060379 seconds
Items processed: 198
Time taken: 591.1300618648529 seconds
Items processed: 199
Time taken: 591.192831993103 seconds
Items processed: 200
Time taken: 592.4136478900909 seconds
Items processed: 201
Time taken: 594.1287441253662 seconds
Items processed: 202
Time taken: 602.4126491546631 seconds
Items processed: 203
Time taken: 602.4187140464783 seconds
Items processed: 204
Time taken: 604.1321949958801 seconds
Items processed: 205
Time taken: 604.2209539413452 seconds
Items processed: 206

In [30]:
len(train_audio_df)

32948

In [ ]:
# Because this dataframe is very large, we save it as a csv file
# so that we can load it later without having to run the above code again.

train_audio_df.to_csv("train_audio_df.csv", index=False)

In [17]:
# Loading the folder

train_audio_df = pd.read_csv("train_audio_df.csv")

In [18]:
train_audio_df.head(5)

               filename primary_label
0  crebec1/XC119358.ogg          Aves
1  crebec1/XC602873.ogg          Aves
2  crebec1/XC844032.ogg          Aves
3  crebec1/XC611358.ogg          Aves
4  crebec1/XC995496.ogg          Aves

In [31]:
NUM_CLASSES = 5
SR = 32000
N_MELS = 128
X_multi = []
y_multi = []

# This loop converts each audio file in train_soundscapes into a mel spectrogram.

for filename in train_soundscapes_reduced_df['filename']:
    file = filename[:-8]
    start = int(filename[-2:])
    
    audio, _ = librosa.load(
        f"train_soundscapes/{file}",
        sr=SR,
        offset=start,
        duration=5
    )

# Converts the audio to a mel spectrogram, and normalizes it to the range [0, 1].

    mel = librosa.feature.melspectrogram(y=audio, sr=SR, n_mels=N_MELS)
    mel_db = librosa.power_to_db(mel, ref=np.max)
    mel_db = (mel_db - mel_db.min()) / (mel_db.max() - mel_db.min())

    X_multi.append(mel_db[..., np.newaxis])

    # 🔥 MULTI-LABEL TARGET
    label_vector = [0] * NUM_CLASSES
    for i, cls in enumerate(classes):
        if filename in filenames[cls]:
            label_vector[i] = 1

    y_multi.append(label_vector)
    
X_multi = np.array(X_multi, dtype=np.float32)
y_multi = np.array(y_multi, dtype=np.float32)

# X is the list of spectrograms, and y is the list of multi-label vectors.

In [ ]:
# We repeat the same process for the audio files in train_audio_df.
# This code is somewhat inefficient, but we only have to run it once.
# It takes 13 minutes to run this code.

from time import time

count = 0
X_single = []
y_single = []
t = time()

EXPECTED_FRAMES = int(np.ceil((SR * 5) / 512))

for row in train_audio_df.itertuples():
    count += 1
    if count%100 == 0:
        print(count, time() - t)
    filename = row.filename
    
    audio, _ = librosa.load(
        f"train_audio/{filename}",
        sr=SR
    )

# After breaking the audio files into 5 second chunks, there were far too many files.
# Rather than processing every file, we take a few chunks.
# If the file is less than 15 seconds, we take 1 chunk. Otherwise, we take 2.

    chunk_length = 5 * SR

    if len(audio) < 2 * chunk_length:
        # 5–10 sec → just take first chunk
        audio_clips = [audio[:chunk_length]]

    elif len(audio) < 3 * chunk_length:
        # 10–15 sec → allow overlap (random is fine)
        audio_clips = []
        for _ in range(2):
            start = np.random.randint(0, len(audio) - chunk_length)
            audio_clips.append(audio[start:start + chunk_length])

    else:
        # ≥15 sec → enforce separation safely
        start1 = np.random.randint(0, len(audio) - chunk_length)
        start2 = np.random.randint(0, len(audio) - chunk_length)

        # Try a few times only (avoid slow loops)
        for _ in range(5):
            if abs(start1 - start2) >= chunk_length:
                break
            start2 = np.random.randint(0, len(audio) - chunk_length)

        audio_clips = [audio[start1:start1 + chunk_length], audio[start2:start2 + chunk_length]]

# Converts the audio files in audio_clips to a mel spectrogram, and normalizes it to the range [0, 1].

    for audio_clip in audio_clips:

        mel = librosa.feature.melspectrogram(
            y=audio_clip,
            sr=SR,
            n_mels=N_MELS
        )

        mel_db = librosa.power_to_db(mel, ref=np.max)
        mel_db = (mel_db - mel_db.min()) / (mel_db.max() - mel_db.min())

        # Pad / trim
        if mel_db.shape[1] < EXPECTED_FRAMES:
            mel_db = np.pad(mel_db, ((0, 0), (0, EXPECTED_FRAMES - mel_db.shape[1])))
        else:
            mel_db = mel_db[:, :EXPECTED_FRAMES]

        X_single.append(mel_db[..., np.newaxis])

        label_vector = [0] * NUM_CLASSES
        for j, cls in enumerate(classes):
            if row.primary_label == cls:
                label_vector[j] = 1

        y_single.append(label_vector)

X_single = np.array(X_single, dtype=np.float32)
y_single = np.array(y_single, dtype=np.float32)

100 2.483482837677002
200 4.973445892333984
300 7.491352081298828
400 9.754539966583252
500 11.502514839172363
600 13.653581857681274
700 16.47809386253357
800 18.275458097457886
900 20.241528749465942
1000 22.42976999282837
1100 24.530609846115112
1200 26.498512983322144
1300 28.753445863723755
1400 31.197897911071777
1500 35.06235074996948
1600 37.5367329120636
1700 40.37897300720215
1800 43.171833753585815
1900 46.17383289337158
2000 48.12741994857788
2100 50.471137046813965
2200 52.6482298374176
2300 54.901602029800415
2400 56.583648920059204
2500 58.24816107749939
2600 61.24835515022278
2700 65.6317389011383
2800 71.61408805847168
2900 74.66432094573975
3000 77.37501096725464
3100 79.33660197257996
3200 81.8761260509491
3300 84.53369975090027
3400 86.54063892364502
3500 89.29617094993591
3600 92.05621409416199
3700 94.75500082969666
3800 96.40390300750732
3900 98.47418808937073
4000 100.47772288322449
4100 102.47477602958679
4200 104.51208186149597
4300 106.41469502449036
4400 108.5849678516388
4500 110.83750796318054
4600 113.00452303886414
4700 115.17573690414429
4800 117.17068076133728
4900 119.85170793533325
5000 123.1964259147644
5100 125.15513181686401
5200 127.25199007987976
5300 129.41808199882507
5400 131.4008870124817
5500 133.68721103668213
5600 136.32432317733765
5700 138.021901845932
5800 139.93691086769104
5900 142.1670069694519
6000 144.21291184425354
6100 146.02362179756165
6200 148.17383694648743
6300 150.14509797096252
6400 152.24595499038696
6500 153.61272501945496
6600 155.68014478683472
6700 158.09043312072754
6800 160.05206203460693
6900 161.74067306518555
7000 163.66118502616882
7100 165.48494911193848
7200 167.16577196121216
7300 168.9244830608368
7400 171.504576921463
7500 173.86287689208984
7600 175.59106492996216
7700 177.0633189678192
7800 178.77365899085999
7900 180.94077014923096
8000 183.03711485862732
8100 185.3566768169403
8200 187.73045778274536
8300 189.76724100112915
8400 191.59332609176636
8500 193.36687397956848
8600 195.60623788833618
8700 197.73295211791992
8800 199.75461292266846
8900 202.52088809013367
9000 204.39190411567688
9100 206.75610494613647
9200 208.61554193496704
9300 210.55174779891968
9400 212.70126008987427
9500 215.26447105407715
9600 217.54327607154846
9700 219.85249209403992
9800 222.38612580299377
9900 224.404611825943
10000 226.78843998908997
10100 228.91207885742188
10200 230.7600598335266
10300 232.4389088153839
10400 234.14801788330078
10500 236.41542887687683
10600 238.58782601356506
10700 240.172602891922
10800 242.91297578811646
10900 245.19351506233215
11000 247.60078501701355
11100 250.59687399864197
11200 253.29322290420532
11300 255.466246843338
11400 257.71364998817444
11500 259.9493329524994
11600 261.8599350452423
11700 264.06101989746094
11800 266.2821168899536
11900 267.9797377586365
12000 269.6074299812317
12100 272.0178029537201
12200 275.12206172943115
12300 277.4484758377075
12400 279.2648048400879
12500 280.92405676841736
12600 283.18819880485535
12700 285.52129101753235
12800 287.21284103393555
12900 289.24549198150635
13000 291.2393798828125
13100 293.2941949367523
13200 295.2306299209595
13300 296.9664011001587
13400 299.0786590576172
13500 301.0656020641327
13600 303.17234683036804
13700 305.286682844162
13800 307.42111587524414
13900 310.1350448131561
14000 312.5030767917633
14100 315.0478777885437
14200 317.63399600982666
14300 319.89424204826355
14400 322.03937315940857
14500 324.4009349346161
14600 326.50970911979675
14700 327.8502731323242
14800 329.2900171279907
14900 330.6494369506836
15000 332.4609191417694
15100 335.07403898239136
15200 337.184611082077
15300 339.432324886322
15400 341.6517131328583
15500 343.4915678501129
15600 344.9232771396637
15700 346.6311848163605
15800 348.0701901912689
15900 349.65797781944275
16000 351.30368995666504
16100 353.1404609680176
16200 354.9387619495392
16300 356.83348202705383
16400 359.15634202957153
16500 361.01535201072693
16600 362.925311088562
16700 364.6332621574402
16800 366.5840198993683
16900 368.79389119148254
17000 370.93774700164795
17100 373.17516803741455
17200 375.50514698028564
17300 378.09584498405457
17400 380.19182801246643
17500 382.493047952652
17600 384.74737215042114
17700 386.9112539291382
17800 389.0963189601898
17900 391.40182089805603
18000 393.22117495536804
18100 395.0249788761139
18200 397.2238290309906
18300 399.3487780094147
18400 401.2861671447754
18500 404.35023379325867
18600 407.0688819885254
18700 410.3193008899689
18800 412.02023696899414
18900 414.14924812316895
19000 415.8454668521881
19100 418.0920991897583
19200 420.6060280799866
19300 423.16076588630676
19400 425.70590806007385
19500 428.0745348930359
19600 430.5457179546356
19700 432.94502782821655
19800 435.25045895576477
19900 436.9857089519501
20000 438.81831192970276
20100 440.36250710487366
20200 442.0102310180664
20300 445.5023591518402
20400 448.75791907310486
20500 450.99394488334656
20600 453.31863594055176
20700 455.20993208885193
20800 457.7743248939514
20900 460.4137270450592
21000 462.728266954422
21100 464.8344609737396
21200 466.818767786026
21300 469.25316190719604
21400 471.312952041626
21500 474.0359859466553
21600 476.27125096321106
21700 478.6082899570465
21800 480.98189902305603
21900 482.88067984580994
22000 484.6615159511566
22100 486.9232280254364
22200 489.7408049106598
22300 493.04415702819824
22400 495.4601209163666
22500 498.1786639690399
22600 500.5878109931946
22700 502.91280484199524
22800 505.2831349372864
22900 507.61247277259827
23000 510.0594370365143
23100 512.5791590213776
23200 514.9448609352112
23300 517.3724360466003
23400 519.3667378425598
23500 521.4903619289398
23600 523.6314580440521
23700 526.0360670089722
23800 528.8718018531799
23900 530.7330160140991
24000 532.5608267784119
24100 534.7423408031464
24200 537.088042974472
24300 539.7786130905151
24400 541.4136030673981
24500 543.5473520755768
24600 546.2421088218689
24700 548.5736660957336
24800 550.4530918598175
24900 553.3285908699036
25000 555.7511270046234
25100 558.3027429580688
25200 560.9299631118774
25300 563.0579447746277
25400 569.2638199329376
25500 573.1700479984283
25600 575.6308569908142
25700 577.9504678249359
25800 579.7477750778198
25900 581.9193968772888
26000 584.2026760578156
26100 589.6134519577026
26200 596.5611209869385
26300 598.5821349620819
26400 600.8502941131592
26500 602.5720009803772
26600 604.6066420078278
26700 606.6204349994659
26800 608.5305769443512
26900 610.2531979084015
27000 612.144809961319
27100 614.1551299095154
27200 616.074296951294
27300 618.6169738769531
27400 620.8979079723358
27500 622.637442111969
27600 624.6799519062042
27700 626.4775009155273
27800 628.6822469234467
27900 630.5504009723663
28000 632.4997849464417
28100 634.9126908779144
28200 637.0903108119965
28300 639.5356760025024
28400 641.5417637825012
28500 643.5156478881836
28600 645.1466059684753
28700 647.2353489398956
28800 649.0658729076385
28900 650.8286049365997
29000 652.8398430347443
29100 654.9465370178223
29200 656.976126909256
29300 659.4660737514496
29400 661.6471970081329
29500 663.2665770053864
29600 665.5293569564819
29700 667.6407589912415
29800 670.091875076294
29900 672.4962239265442
30000 674.5445010662079
30100 676.9092109203339
30200 679.0321428775787
30300 681.4357907772064
30400 683.7625639438629
30500 685.6584560871124
30600 687.4267830848694
30700 689.2536468505859
30800 691.3006420135498
30900 693.4561500549316
31000 695.8486888408661
31100 698.3211629390717
31200 700.672159910202
31300 702.9933190345764
31400 704.9747431278229
31500 706.9810388088226
31600 709.0994429588318
31700 710.9792771339417
31800 712.9801909923553
31900 716.0630960464478
32000 718.7605650424957
32100 721.2136771678925
32200 723.8990359306335
32300 725.9321610927582
32400 728.1295471191406
32500 730.2920660972595
32600 732.278865814209
32700 734.4883399009705
32800 736.7328357696533
32900 738.6742589473724

In [22]:
# X contains 61,994 spectograms.
len(X)

61994

In [34]:
# Because it takes so long to generate the X and y arrays, we save them for later.

np.save("X_multi.npy", X_multi)
np.save("y_multi.npy", y_multi)
np.save("X_single.npy", X_single)
np.save("y_single.npy", y_single)

In [ ]:
# To load these arrays later, use the following code.

# IMPORTANT: If you have run the previous blocks in the past, you can start here after importing the packages from Block 1.

X_multi = np.load("X_multi.npy")
y_multi = np.load("y_multi.npy")
X_single = np.load("X_single.npy")
y_single = np.load("y_single.npy")

In [38]:
X = np.concatenate([X_multi, X_single], axis=0)
y = np.concatenate([y_multi, y_single], axis=0)

In [39]:
# We shuffle the elements of X and y so that we do not over-sample certain types of data.

indices = np.arange(len(X))
np.random.shuffle(indices)

X = X[indices]
y = y[indices]

np.save("X.npy", X)
np.save("y.npy", y)

In [40]:
print("Max labels:", y.sum(axis=1).max())
print("Multi-label count:", np.sum(y.sum(axis=1) > 1))

Max labels: 3.0
Multi-label count: 960

In [42]:
# Now that we have all the files, we can make a model.
# In a previous version of the code, we showed that the class weights of each class in our model are as follows.

class_weights = {'Insecta' : 0.8534296, 'Reptilia' : 11.257143, 'Amphibia' : 0.26092714, 'Mammalia' : 4.075862, 'Aves' : 0.7141994}
class_weights_array = np.array([class_weights[cls] for cls in class_weights])

In [43]:
def weighted_bce(y_true, y_pred):
    bce = tf.keras.backend.binary_crossentropy(y_true, y_pred)

    weights = y_true * class_weights_array + (1 - y_true)

    return tf.reduce_mean(bce * weights, axis=-1)

In [45]:
# Performs a train-test split.

N = X.shape[0]

# Split at 80%
split = int(0.8 * N)
train_idx = indices[:split]
test_idx = indices[split:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

In [47]:
# We have far more single class data than multi-class data. An unweighted algorithm will say that a spectrogram is single class far too often.
# This block weights the train and test sets so that the model gets enough multi-class data.

multi_idx = np.where(y_train.sum(axis=1) > 1)[0]
single_idx = np.where(y_train.sum(axis=1) == 1)[0]

# repeat multi-label samples
# mild oversampling
oversampled_idx = np.concatenate([
    single_idx,
    np.repeat(multi_idx, 3)
])

# plus weighting
sample_weights = np.where(y_train.sum(axis=1) > 1, 2.0, 1.0)

np.random.shuffle(oversampled_idx)

X_train = X_train[oversampled_idx]
y_train = y_train[oversampled_idx]

In [ ]:
np.save("X_train.npy", X_train)
np.save("X_test.npy", X_test)
np.save("y_train.npy", y_train)
np.save("y_test.npy", y_test)

In [3]:
# If you have run all of the previous code before, you can start here after running Block 1.

X = np.load("X.npy")
X_train = np.load("X_train.npy")
X_test = np.load("X_test.npy")
y = np.load("y.npy")
y_train = np.load("y_train.npy")
y_test = np.load("y_test.npy")

In [4]:
print(X.shape)        # should be (N, 128, frames, 1)
print(y.shape)        # should be (N, NUM_CLASSES)
print(y.sum(axis=1))  # check how many multi-label samples

(63472, 128, 313, 1)
(63472, 5)
[1. 1. 1. ... 1. 1. 1.]

In [5]:
print("Max labels per sample:", y.sum(axis=1).max())
print("Number of multi-label samples:", np.sum(y.sum(axis=1) > 1))

Max labels per sample: 3.0
Number of multi-label samples: 960

In [6]:
print(len(y.sum(axis=1)))

63472

In [9]:
input_shape = X.shape[1:]  # (128, frames, 1)

NUM_CLASSES = 5

model = models.Sequential([
    layers.Input(shape=input_shape),
    
    layers.Conv2D(32, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(128, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),

    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.4),

    layers.Dense(NUM_CLASSES, activation='sigmoid')  # 🔥 multi-label
])

In [10]:
def weighted_bce(y_true, y_pred):
    bce = tf.keras.backend.binary_crossentropy(y_true, y_pred)
    weights = y_true * class_weights_array + (1 - y_true)
    return tf.reduce_mean(bce * weights, axis=-1)

In [11]:
# Compiles the model.

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss=weighted_bce,
    metrics=[
    tf.keras.metrics.AUC(multi_label=True),
    tf.keras.metrics.Precision(thresholds=0.3),
    tf.keras.metrics.Recall(thresholds=0.3)
]
)

In [12]:
# Sanity check

class_weights = {'Insecta' : 0.8534296, 'Reptilia' : 11.257143, 'Amphibia' : 0.26092714, 'Mammalia' : 4.075862, 'Aves' : 0.7141994}
class_weights_array = np.array([class_weights[cls] for cls in class_weights])
class_weights_array.shape == (NUM_CLASSES,)

True

In [13]:
sample_weights = np.where(y_train.sum(axis=1) > 1, 2.0, 1.0)
len(sample_weights) == len(X_train)

True

In [ ]:
# Trains the model
# This block took 3 hours on a CPU. The model had 97.5% precision and 98.6% recall.

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=15,
    batch_size=64,
    shuffle=True,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=5,
            restore_best_weights=True
        )
    ]
)

Epoch 1/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 920s 1s/step - auc: 0.8240 - loss: 0.1884 - precision: 0.6472 - recall: 0.9371 - val_auc: 0.6231 - val_loss: 0.1391 - val_precision: 0.9461 - val_recall: 0.9391
Epoch 2/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 896s 1s/step - auc: 0.9212 - loss: 0.0713 - precision: 0.9285 - recall: 0.9606 - val_auc: 0.8049 - val_loss: 0.0734 - val_precision: 0.9519 - val_recall: 0.9508
Epoch 3/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 716s 875ms/step - auc: 0.9420 - loss: 0.0594 - precision: 0.9408 - recall: 0.9658 - val_auc: 0.9103 - val_loss: 0.0471 - val_precision: 0.9651 - val_recall: 0.9738
Epoch 4/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 745s 911ms/step - auc: 0.9532 - loss: 0.0513 - precision: 0.9508 - recall: 0.9714 - val_auc: 0.8845 - val_loss: 0.0715 - val_precision: 0.9531 - val_recall: 0.9622
Epoch 5/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 734s 897ms/step - auc: 0.9614 - loss: 0.0456 - precision: 0.9558 - recall: 0.9736 - val_auc: 0.6806 - val_loss: 0.1249 - val_precision: 0.9419 - val_recall: 0.9516
Epoch 6/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 742s 907ms/step - auc: 0.9650 - loss: 0.0416 - precision: 0.9601 - recall: 0.9771 - val_auc: 0.9297 - val_loss: 0.0851 - val_precision: 0.9181 - val_recall: 0.9590
Epoch 7/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 754s 922ms/step - auc: 0.9703 - loss: 0.0397 - precision: 0.9612 - recall: 0.9776 - val_auc: 0.8546 - val_loss: 0.0650 - val_precision: 0.9543 - val_recall: 0.9658
Epoch 8/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 752s 919ms/step - auc: 0.9733 - loss: 0.0358 - precision: 0.9647 - recall: 0.9793 - val_auc: 0.9201 - val_loss: 0.0439 - val_precision: 0.9710 - val_recall: 0.9762
Epoch 9/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 735s 899ms/step - auc: 0.9769 - loss: 0.0334 - precision: 0.9673 - recall: 0.9805 - val_auc: 0.9301 - val_loss: 0.0381 - val_precision: 0.9696 - val_recall: 0.9782
Epoch 10/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 750s 916ms/step - auc: 0.9805 - loss: 0.0311 - precision: 0.9691 - recall: 0.9820 - val_auc: 0.9408 - val_loss: 0.0397 - val_precision: 0.9754 - val_recall: 0.9742
Epoch 11/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 725s 886ms/step - auc: 0.9818 - loss: 0.0298 - precision: 0.9684 - recall: 0.9828 - val_auc: 0.5864 - val_loss: 0.1632 - val_precision: 0.9459 - val_recall: 0.9301
Epoch 12/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 709s 867ms/step - auc: 0.9838 - loss: 0.0273 - precision: 0.9715 - recall: 0.9835 - val_auc: 0.9571 - val_loss: 0.0367 - val_precision: 0.9636 - val_recall: 0.9825
Epoch 13/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 702s 858ms/step - auc: 0.9839 - loss: 0.0262 - precision: 0.9725 - recall: 0.9841 - val_auc: 0.9403 - val_loss: 0.0419 - val_precision: 0.9650 - val_recall: 0.9740
Epoch 14/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 711s 869ms/step - auc: 0.9865 - loss: 0.0241 - precision: 0.9744 - recall: 0.9855 - val_auc: 0.8710 - val_loss: 0.0646 - val_precision: 0.9729 - val_recall: 0.9724
Epoch 15/15
818/818 ━━━━━━━━━━━━━━━━━━━━ 770s 941ms/step - auc: 0.9881 - loss: 0.0223 - precision: 0.9749 - recall: 0.9858 - val_auc: 0.9450 - val_loss: 0.0321 - val_precision: 0.9753 - val_recall: 0.9813

In [ ]:
# All of the thresholds performed well, but t = 0.5 performed the best at 0.99138.

y_pred = model.predict(X_test)

# try different thresholds
for t in [0.2, 0.3, 0.4, 0.5]:
    y_bin = (y_pred > t).astype(int)
    print(t, np.mean(y_bin == y_test))

397/397 ━━━━━━━━━━━━━━━━━━━━ 31s 79ms/step
0.2 0.9907837731390311
0.3 0.9911461205198897
0.4 0.991366679795195
0.5 0.9913824340291454

In [16]:
# We save the model. This version replaces the one in kaggle v33026.ipynb.

model.save("best_multilabel_model.keras")

In [ ]:
# This block shows how to load the model for future use.

from tensorflow.keras.models import load_model

model = load_model(
    "best_multilabel_model.keras",
    custom_objects={
        "loss": weighted_binary_crossentropy(class_weights)
    }
)