In [1]:
# This code classifies insect sounds in audio files with insects in them.

import librosa
import numpy as np
import pandas as pd
import os
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

In [2]:
# Lists the types of insects

insects = []

taxonomy_df = pd.read_csv("taxonomy.csv")

for row in taxonomy_df.itertuples():
    insects += (row.class_name == 'Insecta')*[row.primary_label]

In [3]:
insects

['1161364',
 '244024',
 '47158son01',
 '47158son02',
 '47158son03',
 '47158son04',
 '47158son05',
 '47158son06',
 '47158son07',
 '47158son08',
 '47158son09',
 '47158son10',
 '47158son11',
 '47158son12',
 '47158son13',
 '47158son14',
 '47158son15',
 '47158son16',
 '47158son17',
 '47158son18',
 '47158son19',
 '47158son20',
 '47158son21',
 '47158son22',
 '47158son23',
 '47158son24',
 '47158son25',
 '760266']

In [4]:
len(insects)

28

In [5]:
train_soundscapes_labels_df = pd.read_csv("train_soundscapes_labels.csv")

train_soundscapes_reduced_df = pd.DataFrame({
    "filename": train_soundscapes_labels_df.iloc[:, :2].astype(str).agg(''.join, axis=1),
    "primary_label": train_soundscapes_labels_df.iloc[:, 3]
})

In [6]:
# Lists all files in train_soundscapes_reduced_df which contain birds.
# Organizes all insects in these files.

train_soundscapes_insects_df = pd.DataFrame(columns = ['filename', 'primary_label'])

for entry in train_soundscapes_reduced_df.itertuples():
    found_insect = False
    primary_labels = entry.primary_label.split(';')
    row_insects = ''
    
    for label in primary_labels:
        if label in insects:
            if found_insect:
                row_insects += ';'
            found_insect = True
            row_insects += label
    
    if found_insect:
        new_row = pd.DataFrame({'filename': [entry.filename], 'primary_label': [row_insects]})
        train_soundscapes_insects_df = pd.concat([train_soundscapes_insects_df, new_row], ignore_index=True)

In [7]:
train_soundscapes_insects_df.head()

,filename,primary_label
0,BC2026_Train_0005_S08_20250607_070007.ogg00:00:00,47158son15;47158son16;47158son17;47158son25
1,BC2026_Train_0005_S08_20250607_070007.ogg00:00:05,47158son15;47158son16;47158son17;47158son25
2,BC2026_Train_0005_S08_20250607_070007.ogg00:00:10,47158son15;47158son16;47158son25
3,BC2026_Train_0005_S08_20250607_070007.ogg00:00:15,47158son15;47158son16;47158son17;47158son25
4,BC2026_Train_0005_S08_20250607_070007.ogg00:00:20,47158son15;47158son16;47158son17;47158son25

In [13]:
# It is very common to have a sound file with multiple insect species.
# 250 out of 336 files in train_soundscapes_insects_df have multiple insects.

multiple_count = 0

for entry in train_soundscapes_insects_df.itertuples():
    if ';' in entry.primary_label:
        multiple_count += 1

print(multiple_count)

250

In [14]:
len(train_soundscapes_insects_df)

336

In [15]:
# In animal_class_classifier.ipynb, we created train_audio_df.csv.
# Each row in this csv corresponds to an audio file in the train_audio folder along with its class.
# Recall that each file in the train_audio folder has exactly one animal in it.
# This loop identifies all bird files in train_audio_df and writes their primary labels.
# Note that the primary label is just the part of the filename that occurs before the '/'.

train_audio_df = pd.read_csv('train_audio_df.csv')

insect_audio_df = pd.DataFrame(columns = ['filename', 'primary_label'])

for entry in train_audio_df.itertuples():
    if entry.primary_label == 'Insecta':
        new_row = pd.DataFrame({'filename': [entry.filename], 'primary_label': [entry.filename.split('/')[0]]})
        insect_audio_df = pd.concat([insect_audio_df, new_row], ignore_index=True)

In [16]:
# In total, we only have 528 files. 336 are in train_soundscapes_insects_df and 192 are in insect_audio_df.
# Crucially, insect_audio_df contains NONE of the sonotypes.

len(insect_audio_df) # 192 files

192

In [17]:
insect_audio_df.head()

                 filename primary_label
0   244024/iNat407846.ogg        244024
1   244024/iNat769302.ogg        244024
2    244024/iNat18148.ogg        244024
3   244024/iNat544406.ogg        244024
4  244024/iNat1232682.ogg        244024

In [18]:
train_soundscapes_insects_df.to_csv('train_soundscapes_insects_df.csv', index=False)
insect_audio_df.to_csv('insect_audio_df.csv', index=False)

In [19]:
# We count the number of files in each class.

counter = {}
for insect in insects:
    counter[insect] = 0

for label in train_soundscapes_insects_df.primary_label:
    labels = label.split(';')
    for primary_label in labels:
        counter[primary_label] += 1

for label in insect_audio_df.primary_label:
    counter[str(label)] += 1

In [20]:
counter.values()

dict_values([10, 176, 46, 14, 66, 34, 6, 36, 96, 34, 12, 66, 72, 10, 72, 24, 24, 24, 86, 24, 10, 24, 44, 48, 48, 48, 168, 6])

In [21]:
# A common class is any class with at least 30 files. The rest of this code is devoted to classifying the common classes.

common_insects = []
rare_insects = []

threshold = 30

for insect in insects:
    if counter[insect] < threshold:
        rare_insects += [insect]
    else:
        common_insects += [insect]

In [22]:
print(common_insects) # There are 16 common insects and 12 rare insects.
print(len(common_insects))
print(rare_insects)
print(len(rare_insects))

['244024', '47158son01', '47158son03', '47158son04', '47158son06', '47158son07', '47158son08', '47158son10', '47158son11', '47158son13', '47158son17', '47158son21', '47158son22', '47158son23', '47158son24', '47158son25']
16
['1161364', '47158son02', '47158son05', '47158son09', '47158son12', '47158son14', '47158son15', '47158son16', '47158son18', '47158son19', '47158son20', '760266']
12

In [23]:
# We reduce train_soundscapes_insects and insect_audio_df into dataframes that only include the common insects.

train_soundscapes_common_insects_df = pd.DataFrame(columns = ['filename', 'primary_label'])

for entry in train_soundscapes_insects_df.itertuples():
    found_common_insect = False
    primary_labels = entry.primary_label.split(';')
    row_common_insects = ''
    
    for label in primary_labels:
        if label in common_insects:
            if found_common_insect:
                row_common_insects += ';'
            found_common_insect = True
            row_common_insects += label
    
    if found_common_insect:
        new_row = pd.DataFrame({'filename': [entry.filename], 'primary_label': [row_common_insects]})
        train_soundscapes_common_insects_df = pd.concat([train_soundscapes_common_insects_df, new_row], ignore_index=True)

In [24]:
# All of the files in train_soundscapes_insects had a common insect.

print(len(train_soundscapes_insects_df), len(train_soundscapes_common_insects_df))

336 336

In [25]:
train_soundscapes_common_insects_df.head()

                                            filename          primary_label
0  BC2026_Train_0005_S08_20250607_070007.ogg00:00:00  47158son17;47158son25
1  BC2026_Train_0005_S08_20250607_070007.ogg00:00:05  47158son17;47158son25
2  BC2026_Train_0005_S08_20250607_070007.ogg00:00:10             47158son25
3  BC2026_Train_0005_S08_20250607_070007.ogg00:00:15  47158son17;47158son25
4  BC2026_Train_0005_S08_20250607_070007.ogg00:00:20  47158son17;47158son25

In [26]:
common_insect_audio_df = pd.DataFrame(columns = ['filename', 'primary_label'])

for entry in insect_audio_df.itertuples():
    if str(entry.primary_label) in common_insects:
        new_row = pd.DataFrame({'filename': [entry.filename], 'primary_label': [str(entry.primary_label)]})
        common_insect_audio_df = pd.concat([common_insect_audio_df, new_row], ignore_index=True)

In [ ]:
print(len(insect_audio_df), len(common_insect_audio_df)) # 176 out of 192 insect files have a common insect (91.7%)

192 176

In [28]:
common_insect_audio_df.head()

                 filename primary_label
0   244024/iNat407846.ogg        244024
1   244024/iNat769302.ogg        244024
2    244024/iNat18148.ogg        244024
3   244024/iNat544406.ogg        244024
4  244024/iNat1232682.ogg        244024

In [31]:
# We now have all the audio files (train_soundscapes_common_insects_df and common_insect_audio_df).

NUM_CLASSES = len(common_insects)
SR = 32000
N_MELS = 128
X_multi = []
y_multi = []

# This loop converts each audio file in train_soundscapes_common_insects_df to a mel spectrogram.

for row in train_soundscapes_common_insects_df.itertuples():
    filename = row.filename
    labels = row.primary_label.split(';')
    file = filename[:-8]
    start = int(filename[-2:])
    
    audio, _ = librosa.load(
        f"train_soundscapes/{file}",
        sr=SR,
        offset=start,
        duration=5
    )

# Converts the audio to a mel spectrogram, and normalizes it to the range [0, 1].

    mel = librosa.feature.melspectrogram(y=audio, sr=SR, n_mels=N_MELS)
    mel_db = librosa.power_to_db(mel, ref=np.max)

    X_multi.append(mel_db[..., np.newaxis])
    
    # 🔥 MULTI-LABEL TARGET
    label_vector = [0] * NUM_CLASSES
    for i, insect in enumerate(common_insects):
        if insect in labels:
            label_vector[i] = 1

    y_multi.append(label_vector)
    
X_multi = np.array(X_multi, dtype=np.float32)
y_multi = np.array(y_multi, dtype=np.float32)

# X is the list of spectrograms, and y is the list of multi-label vectors.

In [32]:
len(y_multi)

336

In [45]:
# We repeat the same process for the audio files in common_bird_audio_df.
# Because these files are longer than 5 seconds, we split them into 5 second chunks.

X_single = []
y_single = []

EXPECTED_FRAMES = int(np.ceil((SR * 5) / 512))

for row in common_insect_audio_df.itertuples():    
    filename = row.filename
    label = row.primary_label
    
    audio, _ = librosa.load(
        f"train_audio/{filename}",
        sr=SR
    )

    chunk_length = 5 * SR
    
    # In animal_class_classifier, we ensured that all of the ogg files were at least five seconds long.
    audio_clips = []
    for i in range(int(len(audio)/chunk_length)):
        audio_clips += [audio[i*chunk_length:(i + 1)*chunk_length]]

    # Converts the audio files in audio_clips to a mel spectrogram, and normalizes it to the range [0, 1].

    for audio_clip in audio_clips:
        mel = librosa.feature.melspectrogram(
            y=audio_clip,
            sr=SR,
            n_mels=N_MELS
        )

        mel_db = librosa.power_to_db(mel, ref=np.max)

        # Pad / trim
        if mel_db.shape[1] < EXPECTED_FRAMES:
            mel_db = np.pad(mel_db, ((0, 0), (0, EXPECTED_FRAMES - mel_db.shape[1])))
        else:
            mel_db = mel_db[:, :EXPECTED_FRAMES]

        X_single.append(mel_db[..., np.newaxis])

        label_vector = [0] * NUM_CLASSES
        for j, insect in enumerate(common_insects):
            if insect == label:
                label_vector[j] = 1

        y_single.append(label_vector)

X_single = np.array(X_single, dtype=np.float32)
y_single = np.array(y_single, dtype=np.float32)

In [46]:
print(len(y_single)) # We have 336 multi-class files and 970 single class files.

970

In [47]:
X = np.concatenate([X_multi, X_single], axis=0)
y = np.concatenate([y_multi, y_single], axis=0)

In [48]:
len(y)

1306

In [49]:
print((y.sum(axis=0) == 0).sum())

0

In [50]:
print((y_multi.sum(axis=0) == 0).sum()) # 1 class appears in single-class files, but not multi-class files.

1

In [51]:
print((y_single.sum(axis=0) == 0).sum()) # 15 of the classes appear in multi-class files, but not single-class files.

15

In [52]:
# We shuffle the elements of X and y so that we do not over-sample certain types of data.

indices = np.arange(len(X))
np.random.shuffle(indices)

X = X[indices]
y = y[indices]

np.save("X_insect.npy", X)
np.save("y_insect.npy", y)

In [ ]:
# To load the arrays, use this block.

X = np.load("X_insect.npy")
y = np.load("y_insect.npy")

In [ ]:
# Performs a train-test-validation split. We skip SpecAugment because the rest of the code works well without it.

# Step 1: Train vs temp (val + test)

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    shuffle=True
)

# Step 2: Test vs val

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    random_state=42,
    shuffle=True
)

X_train = preprocess(X_train)

In [59]:
print("Train zero classes:", np.sum(y_train.sum(axis=0) == 0))
print("Val zero classes:", np.sum(y_val.sum(axis=0) == 0))
print("Test zero classes:", np.sum(y_test.sum(axis=0) == 0))

print("Train counts:", y_train.sum(axis=0))
print("Val counts:", y_val.sum(axis=0))
print("Test counts:", y_test.sum(axis=0))

Train zero classes: 0
Val zero classes: 0
Test zero classes: 0
Train counts: [690.  30.  46.  24.  24.  63.  25.  42.  52.  46.  57.  26.  29.  29.
  34. 109.]
Val counts: [147.   5.   8.   6.   5.  12.   3.  12.   9.  14.  15.   9.   9.   9.
   7.  26.]
Test counts: [133.  11.  12.   4.   7.  21.   6.  12.  11.  12.  14.   9.  10.  10.
   7.  33.]

In [60]:
# Class 0 (244024) is very overrepresented. In light of this fact, we make two models.
# Model A determines the likelihood that class 0 is present in the audio file.
# Model B determines the likelihood that each of the other 15 classes is present in the audio file.

# Class 0 detector
y_train_0 = y_train[:, 0]
y_val_0   = y_val[:, 0]

# Other-class classifier
X_train_other = X_train
y_train_other = y_train[:, 1:]

X_val_other = X_val
y_val_other = y_val[:, 1:]

In [62]:
# The class0 model determines the likelihood that class 0 is present in the audio file. It is a binary classifier.

def build_class0_model(input_shape=(128, 313, 1)):
    inputs = tf.keras.Input(shape=input_shape)

    x = layers.Conv2D(16, (3,3), padding='same')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D((2,2))(x)

    x = layers.Conv2D(32, (3,3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D((2,2))(x)

    x = layers.Conv2D(64, (3,3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D((2,2))(x)

    x = layers.Conv2D(128, (3,3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.GlobalAveragePooling2D()(x)

    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.3)(x)

    outputs = layers.Dense(1, activation='sigmoid')(x)

    return tf.keras.Model(inputs, outputs)

In [63]:
model_a = build_class0_model()

model_a.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.AUC(curve="ROC", name="roc_auc"),
        tf.keras.metrics.AUC(curve="PR", name="pr_auc"),
        tf.keras.metrics.Precision(),
        tf.keras.metrics.Recall()
    ]
)

In [65]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_pr_auc',
        patience=8,
        min_delta=0.0005,
        mode='max',
        restore_best_weights=True,
        verbose=1
    ),
    
    tf.keras.callbacks.ReduceLROnPlateau( # This block reduces the learning rate near the solution
        monitor='val_loss',
        factor=0.5,
        patience=3,
        cooldown=1,
        mode='min',
        min_lr=1e-6,
        verbose=1
    ),
    
    tf.keras.callbacks.ModelCheckpoint(
        'best_class0_model.keras',
        monitor='val_pr_auc',
        mode='max',
        save_best_only=True,
        verbose=1
    )
]

In [66]:
model_a.fit(
    X_train, y_train_0,
    validation_data=(X_val, y_val_0),
    batch_size=32,
    epochs=30,
    callbacks=callbacks
)

Epoch 1/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step - loss: 0.4924 - pr_auc: 0.9242 - precision: 0.8325 - recall: 0.9054 - roc_auc: 0.8049
Epoch 1: val_pr_auc improved from None to 0.97563, saving model to best_class0_model.keras

Epoch 1: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 8s 224ms/step - loss: 0.4198 - pr_auc: 0.9617 - precision: 0.8902 - recall: 0.9043 - roc_auc: 0.8967 - val_loss: 0.6278 - val_pr_auc: 0.9756 - val_precision: 0.7500 - val_recall: 1.0000 - val_roc_auc: 0.9217 - learning_rate: 1.0000e-04
Epoch 2/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - loss: 0.2885 - pr_auc: 0.9830 - precision: 0.9508 - recall: 0.9284 - roc_auc: 0.9612
Epoch 2: val_pr_auc improved from 0.97563 to 0.99222, saving model to best_class0_model.keras

Epoch 2: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 213ms/step - loss: 0.2705 - pr_auc: 0.9854 - precision: 0.9639 - recall: 0.9275 - roc_auc: 0.9650 - val_loss: 0.5210 - val_pr_auc: 0.9922 - val_precision: 0.7500 - val_recall: 1.0000 - val_roc_auc: 0.9727 - learning_rate: 1.0000e-04
Epoch 3/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - loss: 0.2370 - pr_auc: 0.9911 - precision: 0.9653 - recall: 0.9444 - roc_auc: 0.9687
Epoch 3: val_pr_auc improved from 0.99222 to 0.99272, saving model to best_class0_model.keras

Epoch 3: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 213ms/step - loss: 0.2214 - pr_auc: 0.9905 - precision: 0.9609 - recall: 0.9623 - roc_auc: 0.9741 - val_loss: 0.5478 - val_pr_auc: 0.9927 - val_precision: 0.7500 - val_recall: 1.0000 - val_roc_auc: 0.9728 - learning_rate: 1.0000e-04
Epoch 4/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - loss: 0.1856 - pr_auc: 0.9949 - precision: 0.9817 - recall: 0.9560 - roc_auc: 0.9857
Epoch 4: val_pr_auc improved from 0.99272 to 0.99323, saving model to best_class0_model.keras

Epoch 4: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 220ms/step - loss: 0.1847 - pr_auc: 0.9938 - precision: 0.9708 - recall: 0.9623 - roc_auc: 0.9838 - val_loss: 0.4878 - val_pr_auc: 0.9932 - val_precision: 0.7500 - val_recall: 1.0000 - val_roc_auc: 0.9749 - learning_rate: 1.0000e-04
Epoch 5/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - loss: 0.1462 - pr_auc: 0.9974 - precision: 0.9904 - recall: 0.9719 - roc_auc: 0.9921
Epoch 5: val_pr_auc improved from 0.99323 to 0.99463, saving model to best_class0_model.keras

Epoch 5: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 213ms/step - loss: 0.1416 - pr_auc: 0.9973 - precision: 0.9840 - recall: 0.9797 - roc_auc: 0.9926 - val_loss: 0.3565 - val_pr_auc: 0.9946 - val_precision: 0.7617 - val_recall: 1.0000 - val_roc_auc: 0.9810 - learning_rate: 1.0000e-04
Epoch 6/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step - loss: 0.1176 - pr_auc: 0.9986 - precision: 0.9894 - recall: 0.9841 - roc_auc: 0.9958
Epoch 6: val_pr_auc improved from 0.99463 to 0.99610, saving model to best_class0_model.keras

Epoch 6: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 221ms/step - loss: 0.1170 - pr_auc: 0.9985 - precision: 0.9898 - recall: 0.9841 - roc_auc: 0.9953 - val_loss: 0.2292 - val_pr_auc: 0.9961 - val_precision: 0.9530 - val_recall: 0.9660 - val_roc_auc: 0.9869 - learning_rate: 1.0000e-04
Epoch 7/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step - loss: 0.1015 - pr_auc: 0.9988 - precision: 0.9895 - recall: 0.9856 - roc_auc: 0.9967
Epoch 7: val_pr_auc improved from 0.99610 to 0.99750, saving model to best_class0_model.keras

Epoch 7: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 233ms/step - loss: 0.0959 - pr_auc: 0.9992 - precision: 0.9913 - recall: 0.9855 - roc_auc: 0.9975 - val_loss: 0.2452 - val_pr_auc: 0.9975 - val_precision: 1.0000 - val_recall: 0.8844 - val_roc_auc: 0.9919 - learning_rate: 1.0000e-04
Epoch 8/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - loss: 0.0706 - pr_auc: 0.9998 - precision: 0.9952 - recall: 0.9976 - roc_auc: 0.9995
Epoch 8: val_pr_auc did not improve from 0.99750
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 217ms/step - loss: 0.0710 - pr_auc: 0.9998 - precision: 0.9942 - recall: 0.9986 - roc_auc: 0.9994 - val_loss: 0.3018 - val_pr_auc: 0.9974 - val_precision: 1.0000 - val_recall: 0.8299 - val_roc_auc: 0.9916 - learning_rate: 1.0000e-04
Epoch 9/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step - loss: 0.0837 - pr_auc: 0.9992 - precision: 0.9887 - recall: 0.9824 - roc_auc: 0.9972
Epoch 9: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.

Epoch 9: val_pr_auc improved from 0.99750 to 0.99942, saving model to best_class0_model.keras

Epoch 9: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 229ms/step - loss: 0.0763 - pr_auc: 0.9994 - precision: 0.9898 - recall: 0.9870 - roc_auc: 0.9981 - val_loss: 0.2852 - val_pr_auc: 0.9994 - val_precision: 1.0000 - val_recall: 0.8571 - val_roc_auc: 0.9982 - learning_rate: 1.0000e-04
Epoch 10/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step - loss: 0.0536 - pr_auc: 0.9999 - precision: 0.9963 - recall: 0.9930 - roc_auc: 0.9996
Epoch 10: val_pr_auc improved from 0.99942 to 1.00000, saving model to best_class0_model.keras

Epoch 10: finished saving model to best_class0_model.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 225ms/step - loss: 0.0549 - pr_auc: 0.9999 - precision: 0.9942 - recall: 0.9942 - roc_auc: 0.9996 - val_loss: 0.2346 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.8639 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 11/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 232ms/step - loss: 0.0441 - pr_auc: 1.0000 - precision: 0.9980 - recall: 0.9944 - roc_auc: 0.9998
Epoch 11: val_pr_auc did not improve from 1.00000
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 242ms/step - loss: 0.0492 - pr_auc: 0.9999 - precision: 0.9957 - recall: 0.9957 - roc_auc: 0.9998 - val_loss: 0.1875 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.9048 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 12/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step - loss: 0.0423 - pr_auc: 1.0000 - precision: 0.9981 - recall: 0.9979 - roc_auc: 0.9998
Epoch 12: val_pr_auc did not improve from 1.00000
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 219ms/step - loss: 0.0470 - pr_auc: 0.9999 - precision: 0.9942 - recall: 0.9971 - roc_auc: 0.9997 - val_loss: 0.1651 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.9048 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 13/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 214ms/step - loss: 0.0446 - pr_auc: 0.9999 - precision: 0.9962 - recall: 0.9978 - roc_auc: 0.9997
Epoch 13: val_pr_auc did not improve from 1.00000
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 223ms/step - loss: 0.0449 - pr_auc: 0.9999 - precision: 0.9957 - recall: 0.9971 - roc_auc: 0.9997 - val_loss: 0.1284 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.9116 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 14/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - loss: 0.0440 - pr_auc: 1.0000 - precision: 0.9978 - recall: 0.9951 - roc_auc: 0.9999
Epoch 14: val_pr_auc did not improve from 1.00000
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 225ms/step - loss: 0.0433 - pr_auc: 1.0000 - precision: 0.9971 - recall: 0.9957 - roc_auc: 0.9999 - val_loss: 0.1202 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.9116 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 15/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - loss: 0.0310 - pr_auc: 1.0000 - precision: 0.9974 - recall: 0.9977 - roc_auc: 0.9999
Epoch 15: val_pr_auc did not improve from 1.00000
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 241ms/step - loss: 0.0367 - pr_auc: 0.9999 - precision: 0.9957 - recall: 0.9957 - roc_auc: 0.9998 - val_loss: 0.1215 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.9116 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 16/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step - loss: 0.0346 - pr_auc: 1.0000 - precision: 0.9988 - recall: 0.9928 - roc_auc: 0.9999
Epoch 16: val_pr_auc did not improve from 1.00000
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 220ms/step - loss: 0.0329 - pr_auc: 1.0000 - precision: 0.9985 - recall: 0.9971 - roc_auc: 0.9999 - val_loss: 0.1287 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.9116 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 17/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step - loss: 0.0304 - pr_auc: 1.0000 - precision: 0.9988 - recall: 0.9958 - roc_auc: 1.0000
Epoch 17: val_pr_auc did not improve from 1.00000
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 227ms/step - loss: 0.0369 - pr_auc: 0.9999 - precision: 0.9957 - recall: 0.9971 - roc_auc: 0.9998 - val_loss: 0.0634 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.9932 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 18/30
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - loss: 0.0308 - pr_auc: 1.0000 - precision: 0.9972 - recall: 1.0000 - roc_auc: 1.0000
Epoch 18: val_pr_auc did not improve from 1.00000
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 213ms/step - loss: 0.0307 - pr_auc: 1.0000 - precision: 0.9957 - recall: 1.0000 - roc_auc: 0.9999 - val_loss: 0.0622 - val_pr_auc: 1.0000 - val_precision: 1.0000 - val_recall: 0.9796 - val_roc_auc: 1.0000 - learning_rate: 5.0000e-05
Epoch 18: early stopping
Restoring model weights from the end of the best epoch: 10.

In [67]:
# The model seems to do well, but here is an additional check.

model_a = tf.keras.models.load_model("best_class0_model.keras")

y_pred_0 = model_a.predict(X_test).ravel()

from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

print("ROC AUC:", roc_auc_score(y_test[:, 0], y_pred_0))
print("PR AUC:", average_precision_score(y_test[:, 0], y_pred_0))

y_bin_0 = (y_pred_0 > 0.5).astype(int)
print(classification_report(y_test[:, 0], y_bin_0))

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
ROC AUC: 0.9849624060150376
PR AUC: 0.9923143722469345
              precision    recall  f1-score   support

         0.0       0.80      0.95      0.87        63
         1.0       0.98      0.89      0.93       133

    accuracy                           0.91       196
   macro avg       0.89      0.92      0.90       196
weighted avg       0.92      0.91      0.91       196

In [69]:
model_a.save("best_insect0_model.keras")

In [70]:
# We now build model B, which determines the likelihood that each of the other 15 classes is present in the audio file.
# It is a multi-label classifier.

y_train_b = y_train[:, 1:]
y_val_b   = y_val[:, 1:]
y_test_b  = y_test[:, 1:]

NUM_B_CLASSES = y_train_b.shape[1]  # 15

In [71]:
def build_model_b(input_shape=(128, 313, 1), num_classes=15):
    inputs = tf.keras.Input(shape=input_shape)

    x = layers.Conv2D(32, (3,3), padding="same")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D((2,2))(x)

    x = layers.Conv2D(64, (3,3), padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D((2,2))(x)

    x = layers.Conv2D(128, (3,3), padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D((2,2))(x)

    x = layers.Conv2D(256, (3,3), padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    x_avg = layers.GlobalAveragePooling2D()(x)
    x_max = layers.GlobalMaxPooling2D()(x)
    x = layers.Concatenate()([x_avg, x_max])

    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.4)(x)

    outputs = layers.Dense(num_classes, activation="sigmoid")(x)

    return tf.keras.Model(inputs, outputs)

In [72]:
model_b = build_model_b(num_classes=NUM_B_CLASSES)

model_b.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.AUC(curve="ROC", multi_label=True, name="roc_auc"),
        tf.keras.metrics.AUC(curve="PR", multi_label=True, name="pr_auc")
    ]
)

In [73]:
callbacks_b = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_pr_auc",
        patience=8,
        min_delta=0.0005,
        mode="max",
        restore_best_weights=True,
        verbose=1
    ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        cooldown=1,
        mode="min",
        min_lr=1e-6,
        verbose=1
    ),

    tf.keras.callbacks.ModelCheckpoint(
        "best_model_b.keras",
        monitor="val_pr_auc",
        mode="max",
        save_best_only=True,
        verbose=1
    )
]

In [74]:
history_b = model_b.fit(
    X_train, y_train_b,
    validation_data=(X_val, y_val_b),
    batch_size=32,
    epochs=40,
    callbacks=callbacks_b
)

Epoch 1/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 556ms/step - loss: 0.6115 - pr_auc: 0.0530 - roc_auc: 0.5550
Epoch 1: val_pr_auc improved from None to 0.19278, saving model to best_model_b.keras

Epoch 1: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 19s 592ms/step - loss: 0.3776 - pr_auc: 0.0689 - roc_auc: 0.6396 - val_loss: 0.2183 - val_pr_auc: 0.1928 - val_roc_auc: 0.8693 - learning_rate: 1.0000e-04
Epoch 2/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 512ms/step - loss: 0.1555 - pr_auc: 0.1635 - roc_auc: 0.8066
Epoch 2: val_pr_auc improved from 0.19278 to 0.21748, saving model to best_model_b.keras

Epoch 2: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 538ms/step - loss: 0.1537 - pr_auc: 0.1988 - roc_auc: 0.8497 - val_loss: 0.1821 - val_pr_auc: 0.2175 - val_roc_auc: 0.8839 - learning_rate: 1.0000e-04
Epoch 3/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 519ms/step - loss: 0.1451 - pr_auc: 0.3250 - roc_auc: 0.8818
Epoch 3: val_pr_auc improved from 0.21748 to 0.24876, saving model to best_model_b.keras

Epoch 3: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 555ms/step - loss: 0.1324 - pr_auc: 0.2944 - roc_auc: 0.9006 - val_loss: 0.1659 - val_pr_auc: 0.2488 - val_roc_auc: 0.8972 - learning_rate: 1.0000e-04
Epoch 4/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 550ms/step - loss: 0.1224 - pr_auc: 0.3560 - roc_auc: 0.9065
Epoch 4: val_pr_auc improved from 0.24876 to 0.32067, saving model to best_model_b.keras

Epoch 4: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 17s 577ms/step - loss: 0.1169 - pr_auc: 0.3647 - roc_auc: 0.9311 - val_loss: 0.1500 - val_pr_auc: 0.3207 - val_roc_auc: 0.9121 - learning_rate: 1.0000e-04
Epoch 5/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 590ms/step - loss: 0.1103 - pr_auc: 0.4556 - roc_auc: 0.9281
Epoch 5: val_pr_auc improved from 0.32067 to 0.37130, saving model to best_model_b.keras

Epoch 5: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 18s 617ms/step - loss: 0.1082 - pr_auc: 0.4411 - roc_auc: 0.9363 - val_loss: 0.1329 - val_pr_auc: 0.3713 - val_roc_auc: 0.9229 - learning_rate: 1.0000e-04
Epoch 6/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 559ms/step - loss: 0.0999 - pr_auc: 0.4341 - roc_auc: 0.9137
Epoch 6: val_pr_auc improved from 0.37130 to 0.42691, saving model to best_model_b.keras

Epoch 6: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 17s 584ms/step - loss: 0.1016 - pr_auc: 0.4907 - roc_auc: 0.9475 - val_loss: 0.1187 - val_pr_auc: 0.4269 - val_roc_auc: 0.9387 - learning_rate: 1.0000e-04
Epoch 7/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 521ms/step - loss: 0.0868 - pr_auc: 0.5589 - roc_auc: 0.9438
Epoch 7: val_pr_auc improved from 0.42691 to 0.64622, saving model to best_model_b.keras

Epoch 7: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 546ms/step - loss: 0.0916 - pr_auc: 0.5685 - roc_auc: 0.9579 - val_loss: 0.1018 - val_pr_auc: 0.6462 - val_roc_auc: 0.9643 - learning_rate: 1.0000e-04
Epoch 8/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 529ms/step - loss: 0.0911 - pr_auc: 0.6706 - roc_auc: 0.9632
Epoch 8: val_pr_auc improved from 0.64622 to 0.81828, saving model to best_model_b.keras

Epoch 8: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 553ms/step - loss: 0.0874 - pr_auc: 0.6243 - roc_auc: 0.9616 - val_loss: 0.0884 - val_pr_auc: 0.8183 - val_roc_auc: 0.9781 - learning_rate: 1.0000e-04
Epoch 9/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 522ms/step - loss: 0.0852 - pr_auc: 0.6874 - roc_auc: 0.9613
Epoch 9: val_pr_auc improved from 0.81828 to 0.89761, saving model to best_model_b.keras

Epoch 9: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 547ms/step - loss: 0.0820 - pr_auc: 0.6685 - roc_auc: 0.9662 - val_loss: 0.0756 - val_pr_auc: 0.8976 - val_roc_auc: 0.9866 - learning_rate: 1.0000e-04
Epoch 10/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 549ms/step - loss: 0.0697 - pr_auc: 0.7212 - roc_auc: 0.9623
Epoch 10: val_pr_auc improved from 0.89761 to 0.92446, saving model to best_model_b.keras

Epoch 10: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 17s 576ms/step - loss: 0.0743 - pr_auc: 0.7112 - roc_auc: 0.9734 - val_loss: 0.0669 - val_pr_auc: 0.9245 - val_roc_auc: 0.9902 - learning_rate: 1.0000e-04
Epoch 11/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 546ms/step - loss: 0.0737 - pr_auc: 0.7222 - roc_auc: 0.9626
Epoch 11: val_pr_auc improved from 0.92446 to 0.93815, saving model to best_model_b.keras

Epoch 11: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 17s 572ms/step - loss: 0.0702 - pr_auc: 0.7364 - roc_auc: 0.9722 - val_loss: 0.0597 - val_pr_auc: 0.9381 - val_roc_auc: 0.9920 - learning_rate: 1.0000e-04
Epoch 12/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 530ms/step - loss: 0.0614 - pr_auc: 0.7585 - roc_auc: 0.9635
Epoch 12: val_pr_auc improved from 0.93815 to 0.94439, saving model to best_model_b.keras

Epoch 12: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 554ms/step - loss: 0.0670 - pr_auc: 0.7470 - roc_auc: 0.9774 - val_loss: 0.0543 - val_pr_auc: 0.9444 - val_roc_auc: 0.9929 - learning_rate: 1.0000e-04
Epoch 13/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 516ms/step - loss: 0.0615 - pr_auc: 0.7712 - roc_auc: 0.9527
Epoch 13: val_pr_auc improved from 0.94439 to 0.94864, saving model to best_model_b.keras

Epoch 13: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 539ms/step - loss: 0.0636 - pr_auc: 0.7810 - roc_auc: 0.9787 - val_loss: 0.0490 - val_pr_auc: 0.9486 - val_roc_auc: 0.9936 - learning_rate: 1.0000e-04
Epoch 14/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 498ms/step - loss: 0.0627 - pr_auc: 0.7574 - roc_auc: 0.9643
Epoch 14: val_pr_auc improved from 0.94864 to 0.95868, saving model to best_model_b.keras

Epoch 14: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 522ms/step - loss: 0.0612 - pr_auc: 0.7785 - roc_auc: 0.9803 - val_loss: 0.0458 - val_pr_auc: 0.9587 - val_roc_auc: 0.9946 - learning_rate: 1.0000e-04
Epoch 15/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 510ms/step - loss: 0.0638 - pr_auc: 0.7997 - roc_auc: 0.9755
Epoch 15: val_pr_auc did not improve from 0.95868
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 534ms/step - loss: 0.0581 - pr_auc: 0.8047 - roc_auc: 0.9849 - val_loss: 0.0415 - val_pr_auc: 0.9540 - val_roc_auc: 0.9943 - learning_rate: 1.0000e-04
Epoch 16/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 490ms/step - loss: 0.0575 - pr_auc: 0.7961 - roc_auc: 0.9639
Epoch 16: val_pr_auc did not improve from 0.95868
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 513ms/step - loss: 0.0579 - pr_auc: 0.8023 - roc_auc: 0.9815 - val_loss: 0.0399 - val_pr_auc: 0.9555 - val_roc_auc: 0.9967 - learning_rate: 1.0000e-04
Epoch 17/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 492ms/step - loss: 0.0550 - pr_auc: 0.8350 - roc_auc: 0.9771
Epoch 17: val_pr_auc did not improve from 0.95868
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 515ms/step - loss: 0.0550 - pr_auc: 0.8381 - roc_auc: 0.9850 - val_loss: 0.0362 - val_pr_auc: 0.9564 - val_roc_auc: 0.9960 - learning_rate: 1.0000e-04
Epoch 18/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 501ms/step - loss: 0.0539 - pr_auc: 0.8444 - roc_auc: 0.9816
Epoch 18: val_pr_auc improved from 0.95868 to 0.95888, saving model to best_model_b.keras

Epoch 18: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 528ms/step - loss: 0.0503 - pr_auc: 0.8600 - roc_auc: 0.9871 - val_loss: 0.0339 - val_pr_auc: 0.9589 - val_roc_auc: 0.9978 - learning_rate: 1.0000e-04
Epoch 19/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 540ms/step - loss: 0.0472 - pr_auc: 0.8568 - roc_auc: 0.9740
Epoch 19: val_pr_auc improved from 0.95888 to 0.96072, saving model to best_model_b.keras

Epoch 19: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 565ms/step - loss: 0.0490 - pr_auc: 0.8515 - roc_auc: 0.9860 - val_loss: 0.0323 - val_pr_auc: 0.9607 - val_roc_auc: 0.9973 - learning_rate: 1.0000e-04
Epoch 20/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 519ms/step - loss: 0.0440 - pr_auc: 0.8819 - roc_auc: 0.9905
Epoch 20: val_pr_auc improved from 0.96072 to 0.97250, saving model to best_model_b.keras

Epoch 20: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 543ms/step - loss: 0.0458 - pr_auc: 0.8787 - roc_auc: 0.9924 - val_loss: 0.0305 - val_pr_auc: 0.9725 - val_roc_auc: 0.9982 - learning_rate: 1.0000e-04
Epoch 21/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 491ms/step - loss: 0.0439 - pr_auc: 0.8975 - roc_auc: 0.9861
Epoch 21: val_pr_auc did not improve from 0.97250
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 514ms/step - loss: 0.0425 - pr_auc: 0.8985 - roc_auc: 0.9925 - val_loss: 0.0294 - val_pr_auc: 0.9675 - val_roc_auc: 0.9986 - learning_rate: 1.0000e-04
Epoch 22/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 485ms/step - loss: 0.0443 - pr_auc: 0.8729 - roc_auc: 0.9768
Epoch 22: val_pr_auc did not improve from 0.97250
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 508ms/step - loss: 0.0410 - pr_auc: 0.8834 - roc_auc: 0.9908 - val_loss: 0.0268 - val_pr_auc: 0.9699 - val_roc_auc: 0.9989 - learning_rate: 1.0000e-04
Epoch 23/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 487ms/step - loss: 0.0398 - pr_auc: 0.9047 - roc_auc: 0.9918
Epoch 23: val_pr_auc improved from 0.97250 to 0.97863, saving model to best_model_b.keras

Epoch 23: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 510ms/step - loss: 0.0384 - pr_auc: 0.9068 - roc_auc: 0.9939 - val_loss: 0.0252 - val_pr_auc: 0.9786 - val_roc_auc: 0.9991 - learning_rate: 1.0000e-04
Epoch 24/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 484ms/step - loss: 0.0383 - pr_auc: 0.9068 - roc_auc: 0.9813
Epoch 24: val_pr_auc improved from 0.97863 to 0.98012, saving model to best_model_b.keras

Epoch 24: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 507ms/step - loss: 0.0404 - pr_auc: 0.9026 - roc_auc: 0.9903 - val_loss: 0.0246 - val_pr_auc: 0.9801 - val_roc_auc: 0.9992 - learning_rate: 1.0000e-04
Epoch 25/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 484ms/step - loss: 0.0370 - pr_auc: 0.9148 - roc_auc: 0.9825
Epoch 25: val_pr_auc did not improve from 0.98012
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 506ms/step - loss: 0.0366 - pr_auc: 0.9244 - roc_auc: 0.9943 - val_loss: 0.0230 - val_pr_auc: 0.9789 - val_roc_auc: 0.9991 - learning_rate: 1.0000e-04
Epoch 26/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 483ms/step - loss: 0.0351 - pr_auc: 0.8970 - roc_auc: 0.9845
Epoch 26: val_pr_auc did not improve from 0.98012
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 506ms/step - loss: 0.0364 - pr_auc: 0.9098 - roc_auc: 0.9931 - val_loss: 0.0209 - val_pr_auc: 0.9767 - val_roc_auc: 0.9991 - learning_rate: 1.0000e-04
Epoch 27/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 481ms/step - loss: 0.0364 - pr_auc: 0.9135 - roc_auc: 0.9899
Epoch 27: val_pr_auc improved from 0.98012 to 0.99399, saving model to best_model_b.keras

Epoch 27: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 504ms/step - loss: 0.0354 - pr_auc: 0.9220 - roc_auc: 0.9946 - val_loss: 0.0206 - val_pr_auc: 0.9940 - val_roc_auc: 0.9997 - learning_rate: 1.0000e-04
Epoch 28/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 519ms/step - loss: 0.0343 - pr_auc: 0.9104 - roc_auc: 0.9793
Epoch 28: val_pr_auc did not improve from 0.99399
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 542ms/step - loss: 0.0342 - pr_auc: 0.9225 - roc_auc: 0.9951 - val_loss: 0.0221 - val_pr_auc: 0.9938 - val_roc_auc: 0.9996 - learning_rate: 1.0000e-04
Epoch 29/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 488ms/step - loss: 0.0306 - pr_auc: 0.9064 - roc_auc: 0.9775
Epoch 29: val_pr_auc improved from 0.99399 to 0.99527, saving model to best_model_b.keras

Epoch 29: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 511ms/step - loss: 0.0315 - pr_auc: 0.9259 - roc_auc: 0.9957 - val_loss: 0.0191 - val_pr_auc: 0.9953 - val_roc_auc: 0.9997 - learning_rate: 1.0000e-04
Epoch 30/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 499ms/step - loss: 0.0313 - pr_auc: 0.9517 - roc_auc: 0.9923
Epoch 30: val_pr_auc did not improve from 0.99527
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 524ms/step - loss: 0.0287 - pr_auc: 0.9484 - roc_auc: 0.9968 - val_loss: 0.0197 - val_pr_auc: 0.9867 - val_roc_auc: 0.9996 - learning_rate: 1.0000e-04
Epoch 31/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 536ms/step - loss: 0.0322 - pr_auc: 0.9452 - roc_auc: 0.9924
Epoch 31: val_pr_auc did not improve from 0.99527
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 563ms/step - loss: 0.0283 - pr_auc: 0.9513 - roc_auc: 0.9973 - val_loss: 0.0173 - val_pr_auc: 0.9916 - val_roc_auc: 0.9997 - learning_rate: 1.0000e-04
Epoch 32/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 502ms/step - loss: 0.0287 - pr_auc: 0.9410 - roc_auc: 0.9970
Epoch 32: val_pr_auc did not improve from 0.99527
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 525ms/step - loss: 0.0286 - pr_auc: 0.9353 - roc_auc: 0.9963 - val_loss: 0.0181 - val_pr_auc: 0.9907 - val_roc_auc: 0.9996 - learning_rate: 1.0000e-04
Epoch 33/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 491ms/step - loss: 0.0286 - pr_auc: 0.9596 - roc_auc: 0.9949
Epoch 33: val_pr_auc improved from 0.99527 to 0.99768, saving model to best_model_b.keras

Epoch 33: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 515ms/step - loss: 0.0261 - pr_auc: 0.9533 - roc_auc: 0.9969 - val_loss: 0.0167 - val_pr_auc: 0.9977 - val_roc_auc: 0.9998 - learning_rate: 1.0000e-04
Epoch 34/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 491ms/step - loss: 0.0231 - pr_auc: 0.9303 - roc_auc: 0.9706
Epoch 34: val_pr_auc did not improve from 0.99768
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 514ms/step - loss: 0.0257 - pr_auc: 0.9513 - roc_auc: 0.9976 - val_loss: 0.0153 - val_pr_auc: 0.9962 - val_roc_auc: 0.9998 - learning_rate: 1.0000e-04
Epoch 35/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 494ms/step - loss: 0.0233 - pr_auc: 0.9448 - roc_auc: 0.9842
Epoch 35: val_pr_auc improved from 0.99768 to 0.99776, saving model to best_model_b.keras

Epoch 35: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 517ms/step - loss: 0.0245 - pr_auc: 0.9571 - roc_auc: 0.9977 - val_loss: 0.0143 - val_pr_auc: 0.9978 - val_roc_auc: 0.9999 - learning_rate: 1.0000e-04
Epoch 36/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 489ms/step - loss: 0.0273 - pr_auc: 0.9395 - roc_auc: 0.9857
Epoch 36: val_pr_auc improved from 0.99776 to 0.99800, saving model to best_model_b.keras

Epoch 36: finished saving model to best_model_b.keras
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 512ms/step - loss: 0.0269 - pr_auc: 0.9467 - roc_auc: 0.9969 - val_loss: 0.0134 - val_pr_auc: 0.9980 - val_roc_auc: 0.9999 - learning_rate: 1.0000e-04
Epoch 37/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 492ms/step - loss: 0.0238 - pr_auc: 0.9438 - roc_auc: 0.9853
Epoch 37: val_pr_auc did not improve from 0.99800
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 515ms/step - loss: 0.0242 - pr_auc: 0.9510 - roc_auc: 0.9963 - val_loss: 0.0142 - val_pr_auc: 0.9980 - val_roc_auc: 0.9999 - learning_rate: 1.0000e-04
Epoch 38/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 490ms/step - loss: 0.0231 - pr_auc: 0.9600 - roc_auc: 0.9870
Epoch 38: val_pr_auc did not improve from 0.99800
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 513ms/step - loss: 0.0225 - pr_auc: 0.9681 - roc_auc: 0.9985 - val_loss: 0.0133 - val_pr_auc: 0.9980 - val_roc_auc: 0.9999 - learning_rate: 1.0000e-04
Epoch 39/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 504ms/step - loss: 0.0214 - pr_auc: 0.9435 - roc_auc: 0.9803
Epoch 39: val_pr_auc did not improve from 0.99800
29/29 ━━━━━━━━━━━━━━━━━━━━ 15s 527ms/step - loss: 0.0242 - pr_auc: 0.9540 - roc_auc: 0.9963 - val_loss: 0.0121 - val_pr_auc: 0.9980 - val_roc_auc: 0.9999 - learning_rate: 1.0000e-04
Epoch 40/40
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 523ms/step - loss: 0.0202 - pr_auc: 0.9614 - roc_auc: 0.9870
Epoch 40: val_pr_auc did not improve from 0.99800
29/29 ━━━━━━━━━━━━━━━━━━━━ 16s 546ms/step - loss: 0.0224 - pr_auc: 0.9610 - roc_auc: 0.9977 - val_loss: 0.0125 - val_pr_auc: 0.9976 - val_roc_auc: 0.9998 - learning_rate: 1.0000e-04
Restoring model weights from the end of the best epoch: 33.

In [77]:
model_b = tf.keras.models.load_model("best_model_b.keras")

y_pred_b = model_b.predict(X_test)

from sklearn.metrics import roc_auc_score, average_precision_score

print("ROC AUC:", roc_auc_score(y_test_b, y_pred_b, average="macro"))
print("PR AUC:", average_precision_score(y_test_b, y_pred_b, average="macro"))

7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 100ms/step
ROC AUC: 0.9805333557588155
PR AUC: 0.9501590523850982

In [78]:
from sklearn.metrics import f1_score
import numpy as np

thresholds_b = []

for i in range(y_test_b.shape[1]):
    best_t = 0.5
    best_f1 = 0

    for t in np.linspace(0.05, 0.9, 50):
        preds = (y_pred_b[:, i] > t).astype(int)
        f1 = f1_score(y_test_b[:, i], preds, zero_division=0)

        if f1 > best_f1:
            best_f1 = f1
            best_t = t

    thresholds_b.append(best_t)
    print(f"Class {i}: threshold={best_t:.3f}, F1={best_f1:.3f}")

Class 0: threshold=0.137, F1=0.900
Class 1: threshold=0.119, F1=0.909
Class 2: threshold=0.206, F1=1.000
Class 3: threshold=0.328, F1=1.000
Class 4: threshold=0.102, F1=1.000
Class 5: threshold=0.067, F1=1.000
Class 6: threshold=0.189, F1=0.960
Class 7: threshold=0.223, F1=0.900
Class 8: threshold=0.085, F1=1.000
Class 9: threshold=0.137, F1=0.966
Class 10: threshold=0.050, F1=0.947
Class 11: threshold=0.067, F1=1.000
Class 12: threshold=0.050, F1=1.000
Class 13: threshold=0.223, F1=0.833
Class 14: threshold=0.137, F1=1.000

In [ ]:
model_b.save("best_insect1_model.keras")